### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by acdehart** [MarvinMessing/DAU-DB-TOOL#4]
Finish implementing button events and signals with designer. Use PySide2 for plumbing.

**Comment by MarvinMessing** [comment]
Note: PySide2.QtCore is fine to use in backend too for signal. This core part is separate from GUI stuff and can be used like any other python library. I haven't found any library with a better, thread safe subscriber/publisher architecture. 

No other PySide2/Qt things should appear in the backend.

**Comment by acdehart** [comment]
![image](https://user-images.githubusercontent.com/7245881/122841985-47c3f100-d2b1-11eb-9d5c-cfab72452304.png)
The signalling to open child windows and for parent windows to update upon children closing works so far.
I can include a short screen capture video to better illustrate the interactions between windows.
Once this is polished, then the models for communicating between front and back end will be next.
