### ISSUE TITLE
Apply code review change requests

### ISSUE THREAD

**Issue by acdehart** [MarvinMessing/DAU-DB-TOOL#5]
- [x] Rewrite logging.warn() so they can be used as popup notifications
- [x] Slim merge_db() method. Check for db compatibility prior to writing any changes.
- [x] Stage commit and allow user to cancel if any conflicts observed
- [x] Add signal methods to hang on user input with popup to resolve potential merge conflicts
- [x] Outsource parse and utility methods

**Comment by MarvinMessing** [comment]
For logging/popup I recommend: 
- Have a model with this structure: model.warning_code = 101.
- Make a signals called "warning_signal" as part of a signals class.
- Make a backend function called "log_warnings". This function should translate warning codes into strings and log them to the log file. 
- Make a frontend function called "display_warnings". This function should translate warning codes into strings and display them on a popup. 
- Somewhere in the some backend startup code put: signals.warning_signal.connect(log_warnings).
- In frontend startup code put: signals.warning_signal.connect(display_warnings).
- Then, whenever you have a warning put: 
            model.warning_code = 102
            signals.warning_signal.emit()

You can do the same with errors.
